Forced CIFS Unlinking
BnR-US-Midwest/BRUSdevice pull request #1
Opened 2024-03-28 18:10 UTC by bolson-BnR

I was setting the CIFS Link and Eject inputs based on the page that was selected on the HMI, mimicking what was done for the DMAX:
![image](https://github.com/BnR-US-Midwest/BRUSdevice/assets/97972289/2fb8b89e-0c7b-4a0b-94eb-958e15f6cd82)
![image](https://github.com/BnR-US-Midwest/BRUSdevice/assets/97972289/f01fb170-12d1-4323-adbf-da394a4105c3)

I was getting error `20730: Device already exists` from DevLink when changing the page quickly, because the Eject command was interrupting the CIFS_LINK state. I also notice that the Update command will kick the FUB back to Idle, even if there was a device linked already. These changes force the FUB to finish the Link and execute the Eject, so it doesn't get stuck the device created and no handle for DevUnlink to use.

2024-03-28 18:13 UTC, bolson-BnR commented
Note to future B&R users of CIFSDevChk: CIFS is only allowed through our firewall if both devices are on a B&R Domain network. My setup includes a PLC plugged into the office ethernet network, and then it can access my laptop's shared folder if I am in the office OR connected via the VPN!

2024-03-28 18:39 UTC, burbradjones reviewed
Great fixes, one question to consider

2024-03-28 18:39 UTC, burbradjones commented on BRUSdevice/Logical/Lib/BRUSdevice/CIFSDevChk.st
> -		END_IF
🟢 removing this ensures the Update command only works in idle
❔ maybe we can still take the update request but populate Info.Status to say that you are only allowed to update when there are no devices linked?

2024-03-28 18:39 UTC, burbradjones commented
> Note to future B&R users of CIFSDevChk: CIFS is only allowed through our firewall if both devices are on a B&R Domain network. My setup includes a PLC plugged into the office ethernet network, and then it can access my laptop's shared folder if I am in the office OR connected via the VPN!

@BaileyHuemann FYI

2024-04-02 20:40 UTC, burbradjones requested changes
also pls increment the library version!

2024-04-12 14:56 UTC, burbradjones approved these changes
lg2m

2024-04-12 14:57 UTC, merged